server:
  port: 8080

springdoc:
  server-url: ${GATEWAY_URL:http://api-gateway:9000}

spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/market-service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:redpanda:29092}
logging:
  level:
    com.back: INFO
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.orm.jdbc.extract: WARN
    org.springframework.transaction.interceptor: WARN
custom:
  services:
    member-url: ${MEMBER_SERVICE_URL:http://member-service:8080}
    post-url: ${POST_SERVICE_URL:http://post-service:8080}
    payout-url: ${PAYOUT_SERVICE_URL:http://payout-service:8080}
    cash-url: ${CASH_SERVICE_URL:http://cash-service:8080}
    market-url: ${MARKET_SERVICE_URL:http://market-service:8080}
