x-service-common: &service-common
  profiles:
    - prod
  environment:
    SPRING_PROFILES_ACTIVE: prod
  env_file:
    - .env

x-build-common: &build-common
  context: .
  dockerfile: Dockerfile

services:
  redpanda:
    image: redpandadata/redpanda:v24.1.1
    container_name: redpanda
    command:
      - redpanda start
      - --smp=1
      - --memory=256M
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"

  redpanda-console:
    image: redpandadata/console:v2.5.2
    container_name: redpanda-console
    depends_on:
      - redpanda
    ports:
      - "8090:8080"
    environment:
      KAFKA_BROKERS: redpanda:29092

  mysql-service:
    profiles:
      - prod
    image: mysql:8.4
    container_name: mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    <<: *service-common
    build:
      <<: *build-common
      args:
        MODULE: api-gateway
    container_name: api-gateway
    image: sik2dev/p-14650-2:api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - member-service
      - post-service
      - payout-service
      - cash-service
      - market-service

  member-service:
    <<: *service-common
    build:
      <<: *build-common
      args:
        MODULE: member-service
    container_name: member-service
    image: sik2dev/p-14650-2:member-service

  post-service:
    <<: *service-common
    build:
      <<: *build-common
      args:
        MODULE: post-service
    container_name: post-service
    image: sik2dev/p-14650-2:post-service

  payout-service:
    <<: *service-common
    build:
      <<: *build-common
      args:
        MODULE: payout-service
    container_name: payout-service
    image: sik2dev/p-14650-2:payout-service

  cash-service:
    <<: *service-common
    build:
      <<: *build-common
      args:
        MODULE: cash-service
    container_name: cash-service
    image: sik2dev/p-14650-2:cash-service

  market-service:
    <<: *service-common
    build:
      <<: *build-common
      args:
        MODULE: market-service
    container_name: market-service
    image: sik2dev/p-14650-2:market-service

volumes:
  mysql-data:
