apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend

resources:
  - namespace.yaml
  - secret.yaml
  - redpanda.yaml
  - mysql.yaml
  - member-service.yaml
  - post-service.yaml
  - payout-service.yaml
  - cash-service.yaml
  - market-service.yaml
  - ingress.yaml
